%YAML 1.1
---

language:
    'de-DE'

mediaType:
    'wav'

ffmpeg:
    path: ../ffmpeg/bin-6.1.1-full/ffmpeg.exe
    filter_path: ../ffmpeg/arnndn
    filter_name: sh
    # std.rnnn
    # bd.rnnn
    # cb.rnnn
    # lq.rnnn
    # mp.rnnn
    # sh.rnnn

dictionary:
    path: ./_dictionary
    file: Dictionary-DATEV.xlsx

trace_all:
    path: ./_traceAll
