# -*- coding: utf-8; mode: yaml; indent-tabs-mode: nil; -*-
%YAML 1.1
---

language:
    'de-DE'

mediaType:
    'wav'

ffmpeg:
    path: ../ffmpeg/bin-6.1.1-full/ffmpeg.exe
    filter_path: ../ffmpeg/arnndn
    filter_name: sh
    # std.rnnn
    # bd.rnnn
    # cb.rnnn
    # lq.rnnn
    # mp.rnnn
    # sh.rnnn

dictionary:
    path: ./_dictionary
    file: Dictionary-DATEV.xlsx

trace_all:
    path: ./_traceAll

######## WHISPER

whisper:
    whisper_type: faster-whisper
    # whisper_type: whisper
    # whisper_type: whisper-timestamped

    use_initial_prompt: True

    faster_whisper:
        cpu_threads: 7
        use_vad: true

        model_base: ../models/faster-whisper

        models:
            path:
                tiny: Systran--faster-whisper-tiny
                base: Systran--faster-whisper-base
                small: Systran--faster-whisper-small
                medium: Systran--faster-whisper-medium
                large-v1: Systran--faster-whisper-large-v1
                large-v2: Systran--faster-whisper-large-v2
                large-v3: Systran--faster-whisper-large-v3

                large-v2•de: Bofenghuang--faster-whisper-large-v2-de

                large-v2•distil: Systran--faster-distil-whisper-large-v2
                large-v3•distil: Systran--faster-distil-whisper-large-v3
                large-v3•destil-de: Primeline--faster-whisper-large-v3-distil-de

                large-v3•turbo: OpenAI--faster-whisper-large-v3-turbo
                large-v3•turbo-de: Primeline--faster-whisper-large-v3-turbo-de
                large-v3•turbo-deepdml: Deepdml--faster-whisper-large-v3-turbo

                large-v3•crisper: Nyrahealth--faster-CrisperWhisper-v3

            files:
            - config.json
            - model.bin
            - tokenizer.json

            no_condition_on_previous_text:
            - large-v3
           # - large-v3•turbo
           # - large-v3•turbo-de
            - large-v3•distil
            - large-v3•destil-de
            - large-v3•crisper

    whisper:
        model_base: ../models/whisper
        models:
            types:
            - tiny
            - small
            - base
            - medium
            - large-v1
            - large-v2
            - large-v3
            - large-v3•turbo

            no_condition_on_previous_text:
            - large-v3
            - large-v3•turbo

######## SPACY

spacy:
    spacy_37:
        model_base: ../models/spacy/spacy-3.7
        model_name:
            de: de_dep_news_trf-3.7.2 # de_core_news_lg-3.7.0
            en: en_core_web_lg-3.7.1

    spacy_38:
        model_base: ../models/spacy/spacy-3.8
        model_name:
            de: de_dep_news_trf-3.8.0 # de_core_news_lg-3.8.0
            en: en_core_web_lg-3.8.0

######## HUNSPELL

hunspell:
    path: ./_hunspell
    file: de-DE
